server:
  port: 8771

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: neo_route
          uri: lb://eureka-client
          filters:
          - AddRequestParameter=name, gateway
          predicates:
          - Method=GET

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



