eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 #客户端心跳时间
    lease-expiration-duration-in-seconds: 20 #服务器未接到心跳的发呆时间
server:
  port: 8764
spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/oil-business?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: airport
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: logback-server
  mvc:
    servlet:
      load-on-startup: 1
mybatis:
  typeAliasesPackage: com.ias.pms.business.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  params: count=countSql

logging:
  level:
    root: INFO
  path: ../logs/oil/
  config: classpath:logback-spring.xml
